import { permissionsSeed } from '@database/postgres/seeder/seeds/permissions.seed';

/**
 * Union type of all possible permission names.
 *
 * This type is automatically inferred from the `permissionsSeed` array,
 * ensuring that permission names stay in sync between:
 * - The database seeder
 * - The Permissions object used in decorators
 *
 * Example:
 * ```ts
 * type TPermissions = "full_access" | "permissions_get_all" | "permissions_get_all";
 * ```
 */
export type TPermissions = (typeof permissionsSeed)[number]['name'];

/**
 * Utility type that maps each permission name (string literal)
 * to its UPPERCASE representation, which will be used as the key
 * inside the `PermissionsConst` object.
 *
 * For example, given a seed entry:
 * ```ts
 * { name: "full_access" }
 * ```
 * This type produces:
 * ```ts
 * "FULL_ACCESS"
 * ```
 *
 * This ensures strong typing and IDE autocomplete when accessing
 * `PermissionsConst.<KEY>` instead of falling back to `string` indexing.
 */
type UppercaseKeys<T extends readonly { name: string }[]> = T[number]['name'] extends infer N
	? N extends string
		? Uppercase<N>
		: never
	: never;

/**
 * Enum-like constant derived from the `permissionsSeed` array.
 *
 * Keys are automatically generated by uppercasing the `name` field
 * of each item in `permissionsSeed`. Values are the original permission names.
 * The object is frozen with `Object.freeze` to prevent modification at runtime.
 *
 * Example:
 * ```ts
 * PermissionsConst.FULL_ACCESS // "full_access"
 * PermissionsConst.PERMISSIONS_GET_ALL // "permissions_get_all"
 * ```
 *
 * This allows usage like:
 * ```ts
 * @PermissionDecorator([PermissionsConst.FULL_ACCESS])
 * ```
 * instead of hardcoding string literals.
 */
export const PermissionsConst = Object.freeze(
	permissionsSeed.reduce(
		(acc, perm) => {
			acc[perm.name.toUpperCase() as UppercaseKeys<typeof permissionsSeed>] = perm.name;
			return acc;
		},
		{} as Record<UppercaseKeys<typeof permissionsSeed>, TPermissions>,
	),
);
